[project]
name = "docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mkdocs==1.5.3",
    "mkdocs-material==9.5.3",
    "pymdown-extensions==10.7",
]
