name: Deploy Vue and MkDocs to GitHub Pages

# 触发条件: push 到 main 分支且相关文件变动
on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'         # 文档源文件变动触发部署
      - 'frontend/**'     # 前端源文件变动触发部署
      - 'docs/requirements.txt' # 文档依赖变动也触发部署
      - '.github/workflows/deploy_vue+docs.yml' # 配置文件变动也触发部署

# 权限设置
permissions:
  contents: read              # 读取仓库内容
  pages: write                # 写入 Pages 发布资源
  id-token: write             # OIDC for GitHub Pages 部署

# 作业流程
jobs:
  deploy:
    # 运行环境
    runs-on: ubuntu-latest
    
    # 环境变量
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # 用于显示部署记录
    
    steps:
      # 克隆仓库源码
      - name: Checkout
        uses: actions/checkout@v4
      
      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      # 设置 Node.js 环境
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      
      # 构建前端静态文件
      - name: Install frontend deps and build
        working-directory: frontend
        run: |
          npm install
          npm run build
      
      # 构建 MkDocs 静态文件到前端的输出目录
      - name: Install MkDocs and build docs
        run: |
          pip install -r docs/requirements.txt
          mkdocs build -d frontend/dist/docs

      # 上传构建产物到官方 GitHub Pages 服务器
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'frontend/dist'

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
